### ISSUE TITLE
retarded paste

### ISSUE THREAD

**Issue by ghost** [SamuelTulach/memhv#2]
At least give credits to the right person......

https://github.com/HoShiMin/Kernel-Bridge/blob/44b130690c5af5c0eb93d54c435087ffad4c79ab/Kernel-Bridge/API/Hypervisor.cpp

**Comment by SamuelTulach** [comment]
<img width="593" alt="Screenshot 2024-04-09 at 9 23 02" src="https://github.com/SamuelTulach/memhv/assets/16323119/c0fa8154-99ef-4a32-99d2-d7cde65f39a0">

Both are "inspired" by SimpleSvm. That's noted both in the README and LICENSE files. Other than that I don't see many similarities? I am not familiar with the project but the hypervisor there seems to be used only for page access interception (EPT/NPT).
