### ISSUE TITLE
BSOD/hang on load

### ISSUE THREAD

**Issue by vanishingfork** [SamuelTulach/memhv#3]
Test signing the driver and loading it gives INVALID_DRIVER_HANDLE nvlddmkm.sys when LaunchVm is called (i think, everything before this executes without crash). When I load with KDMAPPER it just freezes up.

It works in a virtualbox vm with NESTED_MODE true but doesn't work on when loaded on my host machine NESTED_MODE true or false.

Win11 build 10.0.22621

![Screenshot 2024-04-20 175005](https://github.com/SamuelTulach/memhv/assets/162802861/b31765c5-b749-4f1b-bb0f-dc76a8a6c68b)

**Comment by SamuelTulach** [comment]
<img width="331" alt="Screenshot 2024-04-21 at 10 18 56" src="https://github.com/SamuelTulach/memhv/assets/16323119/f18cfeda-0a76-4bf0-8841-6d6499cc18c1">

<img width="859" alt="Screenshot 2024-04-21 at 10 19 59" src="https://github.com/SamuelTulach/memhv/assets/16323119/5e5faed9-88b3-4cfe-9266-50108caf497f">
